version: '2'

services:
  app:
    build: .
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./build:/build
  test-python2:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        PYTHON_VERSION: 2
