version: '2'

services:
  app:
    build: .
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./build:/build
  test-python2:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        PYTHON_VERSION: 2

  test-integration:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./build:/build
    env_file: .env
    entrypoint:
      - sh
      - -c
      - "nosetests --with-xunit --xunit-file=/build/nosetests-integration.xml test_integ; cd /app && python3 -m test_integ.teardown"
